app/Http/routes.php
<?php
Route::any('managepanel', ['as' => 'css.home', 'uses' => 'Auth\AuthController@postLogin']);
Route::get('admin', function () {
    return redirect('managepanel');
});
Route::controller('order-transfer', 'TransferOrderController', [
    'postStatus' => 'transfer.order.status',
    'anyTest'    => 'transferuj.test'
]);

Route::controller('mailgun/events', 'MailgunEventController', [
    'postEvent' => 'mailgun.event.post',
]); 

Route::post('order/get-options', ['as' => 'order.options', 'uses' => 'OrderController@postGetOptions']);

Route::controller('test', 'TestController');

$subdomainRoutes = function () {
    Route::get('masker-hitam', function () {
        return redirect('http://promo-goodies.com/masker-hitam');
    });
    Route::get('masker-hitam1', function () {
        return redirect('http://promo-goodies.com/masker-hitam');
    });
    Route::get('masker-hitam2', function () {
        return redirect('http://promo-goodies.com/masker-hitam');
    });
    Route::get('masker-hitam2_main', function () {
        return redirect('http://promo-goodies.com/masker-hitam');
    });
//    Route::get('thai', ['as' => 'page.maskPreOrderThai', 'uses' => 'WelcomeController@maskPreOrderThai']);

    Route::get('garcinia-cambogia_test', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia1');
    });
    Route::get('garcinia-cambogia_main', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia1');
    });
    Route::get('garcinia-cambogia', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia1');
    });
    Route::get('garcinia-cambogia1', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia1');
    });
    Route::get('garcinia-cambogia1_main', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia1');
    });
    Route::get('garcinia-cambogia2', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
    Route::get('garcinia-cambogia2pop', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
    Route::get('garcinia-cambogia2_main', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
//    Route::get('garcinia-cambogia2_mainpop', ['as' => 'page.garciniaCambogia2_mainpop', 'uses' => 'WelcomeController@garciniaCambogia2_mainpop']);
//    Route::get('garcinia-cambogia2popup', ['as' => 'page.garciniaCambogia2popup', 'uses' => 'WelcomeController@garciniaCambogia2popup']);
    Route::get('garcinia-cambogia2_main1', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
    Route::get('garcinia-cambogia3', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
//    Route::get('garcinia', ['as' => 'page.intro', 'uses' => 'WelcomeController@intro']);
    Route::get('garcinia2', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
    Route::get('garcinia2_main', function () {
        return redirect('http://promo-goodies.com/garcinia-cambogia2');
    });
//    Route::get('anti_oksidan_alami', ['as' => 'page.garcinia_forte', 'uses' => 'WelcomeController@garcinia_forte']);
//    Route::get('garcinia/composition', ['as' => 'page.introcomposition', 'uses' => 'WelcomeController@introcomposition']);
//    Route::get('garcinia/faq', ['as' => 'page.introfaq', 'uses' => 'WelcomeController@introfaq']);
//    Route::get('garcinia/terms-regulations', ['as' => 'page.introterms', 'uses' => 'WelcomeController@introterms']);
//    Route::get('garcinia/terms-cookies', ['as' => 'page.introcookies', 'uses' => 'WelcomeController@introcookies']);
//    Route::get('drhallux/terms-regulations', ['as' => 'page.halluterms', 'uses' => 'WelcomeController@halluterms']);
//    Route::get('drhallux/terms-cookies', ['as' => 'page.hallucookies', 'uses' => 'WelcomeController@hallucookies']);
//    Route::get('garcinia/metamorphosis', ['as' => 'page.intrometamorphosis', 'uses' => 'WelcomeController@intrometamorphosis']);
    Route::get('drhallux', function () {
        return redirect('http://promo-goodies.com/drhallux');
    });
    Route::get('drhallux2', function () {
        return redirect('http://promo-goodies.com/drhallux');
    });
    Route::get('drhallux_1', function () {
        return redirect('http://promo-goodies.com/drhallux');
    });

    Route::get('predrhallux_main', function () {
        return redirect('http://promo-goodies.com/drhallux');
    });

    Route::get('privacy-policy', ['as' => 'page.privacyPolicy', 'uses' => 'WelcomeController@privacyPolicy']);

    Route::get('leadslist', ['as' => 'page.leadslist', 'uses' => 'WelcomeController@leadslist']);
    Route::get('garciniaicc', ['as' => 'page.garciniaicc', 'uses' => 'WelcomeController@garciniaicc']);
    Route::get('blackmaskicc', ['as' => 'page.blackmaskicc', 'uses' => 'WelcomeController@blackmaskicc']);
    Route::post('internalicc/{id}', ['uses' => 'WelcomeController@internaliccForm']);

    Route::get('externalicc', ['as' => 'page.externalicc', 'uses' => 'WelcomeController@externalicc']);
    Route::post('externalicc/{id}', ['uses' => 'WelcomeController@externaliccForm']);

    Route::get('invalidphones', ['as' => 'page.invalidphones', 'uses' => 'WelcomeController@invalidPhones']);

    Route::get('missingareas', ['as' => 'page.missingareas', 'uses' => 'WelcomeController@missingAreas']);

//    Route::get(LaravelLocalization::transRoute('routes.order'), ['as' => 'page.order', 'uses' => 'PageController@orderForm']);
//    Route::get('/order_test', ['as' => 'page.order.test', 'uses' => 'PageController@orderFormTest']);

    Route::any('order/newsletter', ['as' => 'order.newsletter', 'uses' => 'OrderController@postNewsletter']);

    Route::any('confirm', ['as' => 'order.confirm', 'uses' => 'OrderController@postCheckout']);
//    Route::get('/typage', ['as' => 'page.typ', 'uses' => 'PageController@orderTyp']);
    Route::get('checkout/{product}', ['as' => 'page.checkout', 'uses' => 'PageController@orderCheckout']);
    Route::post('checkout/form', ['as' => 'page.checkout.form', 'uses' => 'PageController@postOrderCheckout']);
    Route::get('confirm/{product}/{id}', ['as' => 'page.confirm', 'uses' => 'PageController@orderConfirm']);
//    Route::get('confirm/{product}/{id}&contact_id={contact}', ['as' => 'page.confirm', 'uses' => 'PageController@orderConfirm']);
    Route::post('orderAddress/edit', ['as' => 'page.editOrderAddress', 'uses' => 'PageController@editOrderAddress']);

    Route::get('usersForNewPanel', ['as' => 'get.usersForNewPanel', 'uses' => 'Admin\ExportController@usersForNewPanel']);
//    Route::get('areas', ['as' => 'get.areas', 'uses' => 'Admin\ExportController@areas']);
//    Route::get('mails', ['as' => 'get.mails', 'uses' => 'Admin\ExportController@getMailsFromFile']);
//    Route::get('couriers', ['as' => 'get.couriers', 'uses' => 'Admin\ExportController@getCouriersReport']);
    Route::get('allmails', ['as' => 'get.allMails', 'uses' => 'Admin\ExportController@getMailReport']);
//    Route::get('soldmails', ['as' => 'get.soldMails', 'uses' => 'Admin\ExportController@getMailReportSold']);
//    Route::get('unsoldmails', ['as' => 'get.unsoldMails', 'uses' => 'Admin\ExportController@getMailReportUnsold']);
//    Route::get('params', ['as' => 'get.params', 'uses' => 'Admin\ExportController@getParams']);

    Route::get('api/contact/test/connection', ['as' => 'api.test', 'uses' => 'ExternalClientController@testConnection']);

    Route::post('api/token/generate', ['as' => 'api.generateToken', 'uses' => 'ExternalClientController@generateToken']);
    Route::post('api/make/contact/{product_name?}', ['as' => 'api.makeOrder', 'uses' => 'ExternalClientController@makeContact']);
    Route::post('api/make/contacts', ['as' => 'api.makeOrder', 'uses' => 'ExternalClientController@makeContacts']);
//    Route::post('api/post/status/multiple', ['as' => 'api.postStatusMultiple', 'uses' => 'ExternalClientController@postStatusMultiple']);

    Route::get('api/get/externalCli', ['as' => 'api.makeOrder', 'uses' => 'ExternalClientController@getExternalCli']);

    Route::get('api/send/postBacks', ['as' => 'api.postBacks', 'uses' => 'ExternalClientController@postBacks']);
    Route::post('api/send/postBacks', ['as' => 'api.postBacks', 'uses' => 'ExternalClientController@sendPostBacks']);

    Route::get('api/delivery/{id}', ['as' => 'api.deliveryId', 'uses' => 'Admin\OrderController@getDelivery']);

    Route::post('api/ninja/hook', ['as' => 'api.ninjaHook', 'uses' => 'Admin\OrderController@postNinja']);

//   Route::get('codOrderMade', ['as' => 'get.codOrderMade', 'uses' => 'Admin\ExportController@codOrderMade']);
//   Route::get('codOrderSent', ['as' => 'get.codOrderSent', 'uses' => 'Admin\ExportController@codOrderSent']);
//   Route::get('codOrderDelivered', ['as' => 'get.codOrderDelivered', 'uses' => 'Admin\ExportController@codOrderDelivered']);
//
//   Route::get('noncodOrderMade', ['as' => 'get.noncodOrderMade', 'uses' => 'Admin\ExportController@noncodOrderMade']);
//   Route::get('noncodOrderSent', ['as' => 'get.noncodOrderSent', 'uses' => 'Admin\ExportController@noncodOrderSent']);
//   Route::get('noncodOrderDelivered', ['as' => 'get.noncodOrderDelivered', 'uses' => 'Admin\ExportController@noncodOrderDelivered']);
};

// korting-harga.com -> http://promos-seru.com
Route::group(['domain' =>  env('PROD_URL')], $subdomainRoutes);
// http://penawaran-super.com
Route::group(['domain' =>  env('PROD_URL2')], $subdomainRoutes);

Route::post('pelajaran-sample', ['as' => 'page.try.send', 'uses' => 'WelcomeController@tryLesson']);

// medical-jurnal.com -> http://agenda-kesehatan.com
Route::group(['middleware' => ['promotion']], function () {
    Route::group(
        [
            'prefix'     => LaravelLocalization::setLocale(),

app/Opinion.php
<?php

namespace App;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Carbon\Carbon;

class Opinion extends Model implements Transformable {

    use Translatable, TransformableTrait;

    /**
     * @var string
     */
    protected $table = 'opinions';

    /**
     * @var array
     */
    protected $translatedAttributes = ['name', 'description', 'icon'];

    /**
     * @var array
     */
    protected $fillable = ['name', 'description', 'main', 'icon'];

    /**
     * @var array
     */
    protected $appends = ['created_at_formated'];

    /**
     * @return static
     */
    public function getCreatedAtFormatedAttribute()
    {
        return Carbon::parse($this->created_at);
    }

    /**
     * @return string
     */
    public function getIconPathAttribute()
    {
        return asset('opinions/icons/' . $this->icon);
    }

}

resources/views/part/analytics.blade.php
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    //1 on prod
    ga('create', 'UA-82396380-5', 'auto');
    ga('send', 'pageview');
    ga('require', 'ecommerce');

</script>

resources/views/part/bottom_with_links.blade.php
<section class="possibilities">
	<div class="container">
		<h2>
			{{ trans('welcome.use.possibilities') }} <strong>{{ trans('welcome.krebs.method') }}</strong>
		</h2>

		<div class="links">
			{{--
			<a href="{{ route('page.try') }}" type="button" class="btn btn-blue">{{ trans('welcome.slider.try.lesson') }}</a>
			--}}
			<a href="#" class="btn btn-blue trigger"
			   type="button"
			   data-toggle="modal"
			   data-target="#{{ !Session::has('try')?'try':'test-lesson' }}"
			>
				{{ trans('welcome.slider.try.lesson') }}
			</a>

			<a href="{{ route('page.languages') }}#buy"
			   class="btn btn-green">{{ trans('welcome.buy.now') }}</a>
		</div>
	</div>
</section>

resources/views/part/countdown.blade.php
<script type="text/javascript">function countdown() {
        var e = 3600, n = 60;
        seconds = 1;
        var t = Math.floor((date_for_sale - (new Date).getTime()) / 1e3);
        0 > t && (t = 0), h = Math.floor(t / e), h < 10 && (h = "0" + h), t -= h * e, m = Math.floor(t / n), m < 10 && (m = "0" + m), t -= m * n, s = Math.floor(t / seconds), s < 10 && (s = "0" + s), document.getElementById("hours").innerHTML = h, document.getElementById("min").innerHTML = m, document.getElementById("sec").innerHTML = s, (h > 0 || m > 0 || s > 0 || d > 0) && setTimeout(countdown, 1e3)
    }
    document.addEventListener("DOMContentLoaded", function () {
        date_for_sale = (new Date).getTime(), date_for_sale += 36e5, countdown()
    });
</script>

resources/views/part/detail.blade.php
<li class="col-sm-6 col-md-4 box wow">
	<span class="img">
		<img src="{{ $icon }}" alt="ico"/>
	</span>
	<div class="content">
		<span class="title">
			<h3>{{ $page->title }}</h3>
		</span>
		<p>{!! $page->content !!}</p>
	</div>
</li>

resources/views/part/exit_popup.blade.php
<div class="exitpopup">
    <a class="exitpopup-close"></a>
    <a href="{{ route('order.special') }}" class="exitpopup-buy"></a>
</div>

@section('scripts')
    <script type="text/javascript">

        window.onbeforeunload = (function () {
                var $popup = $('.exitpopup');
                if ($popup.is(':hidden')){
                    $popup.css('left', (window.innerWidth/2 - $popup.width()/2));
                    $popup.css('top', (window.innerHeight/2 - $popup.height()/2));
                    $popup.show();
                    return 'Stay and get extra discount';
                }
        });

        $('.exitpopup-close').click(function () {
            $('.exitpopup').hide();
        });

    </script>
@endsection

resources/views/part/fb_comments.blade.php
<section class="fb-comments">
	<div class="container">
		<div class="fb-comments" data-order-by="time" data-href="http://id.krebsmethod.com/" data-width="100%" data-numposts="5"></div>
	</div>
</section>

resources/views/part/google.blade.php
<!-- Google Code for Remarketing Tag -->
<!--------------------------------------------------
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 873855984;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/873855984/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>

resources/views/part/instagram.blade.php
<section id="more-opinions">

	@foreach($instagramImages as $image)
		<div>
			<span class="img">
				<a href="{{ $image->link }}" target="_blank">
					<img src="{{ $image->images->low_resolution->url }}" alt=""/>
				</a>
			</span>
			<span>{{ LocalizedCarbon::instance(\Carbon\Carbon::createFromTimestamp($image->created_time))->diffForHumans() }}</span>

			<p>@if(isset($image->caption->text)){{ $image->caption->text }}@endif</p>

		</div>
	@endforeach

</section>

resources/views/part/params.blade.php
<input name="params" type="hidden" value="{{ $params }}">

resources/views/part/popup.blade.php
<!-- Wypróbuj -->
@if(isset($languages))
	<div class="modal fade" id="try" tabindex="-1" role="dialog" aria-labelledby="tryLabel">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="tryLabel">{{ trans('try.write.to.get') }}
						<strong>{{ trans('try.free.lesson') }}</strong>
					</h4>
				</div>
				<div class="modal-body">
					{!! form_start($tryForm,['class' => 'modal-form']) !!}

					<div class="lang">
						<p>{{ trans('languages.choose.language') }}</p>

						@foreach($languagesWithSample as $key => $language)
							<label for="lang-{{ $language->id }}" @if($key == 0) class="active" @endif>
								<img src="{{ $language->icon_path }}" alt="">
								<input type="radio" @if($key == 0) checked @endif name="language" id="lang-{{ $language->id }}" value="{{ $language->id }}"/>
							</label>
						@endforeach
					</div>

					{!! form_widget($tryForm->name,['attr' => ['class' => '']]) !!}
					{!! form_widget($tryForm->email,['attr' => ['class' => '']]) !!}
					{!! form_widget($tryForm->phone,['attr' => ['class' => '']]) !!}
					{!! form_widget($tryForm->age,['attr' => ['class' => '']]) !!}



					<div class="other-lang">
						<p>{{ trans('languages.choose.other') }}</p><br>
						<label for="oth-lang-english">
							<img src="{{ asset('build/images/langs/english.png') }}" alt="">
							<br><span>Inggris</span>
							<input type="checkbox" name="other_lang[]" id="oth-lang-english" value="English" />
						</label>

						<label for="oth-lang-german">
							<img src="{{ asset('build/images/langs/german.png') }}" alt="">
							<br><span>Jerman</span>
							<input type="checkbox" name="other_lang[]" id="oth-lang-german" value="German" />
						</label>

						<label for="oth-lang-chinese">
							<img src="{{ asset('build/images/langs/chinese.png') }}" alt="">
							<br><span>Cina</span>
							<input type="checkbox" name="other_lang[]" id="oth-lang-chinese" value="Chinese" />
						</label>

						<label for="oth-lang-japanese">
							<img src="{{ asset('build/images/langs/japanese.png') }}" alt="">
							<br><span>Jepang</span>
							<input type="checkbox" name="other_lang[]" id="oth-lang-japanese" value="Japanese" />
						</label>

						<label for="oth-lang-arab">
							<img src="{{ asset('build/images/langs/arab.png') }}" alt="">
							<br><span>Arab</span>
							<input type="checkbox" name="other_lang[]" id="oth-lang-arab" value="Arab" />
						</label>
					</div>

					{!! form_widget($tryForm->submit,['attr' => ['class' => '']]) !!}
					{!! form_end($tryForm) !!}
				</div>
			</div>
		</div>
	</div>

	<!-- Koniec Wypróbuj -->

	@if(Session::has('try'))
			<!-- Lekcja Próbna -->
	<div class="modal fade" id="test-lesson" tabindex="-1" role="dialog" aria-labelledby="testLesson">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
					<div>
						<!-- Tab panes -->
						<div class="tab-content">
							@foreach($languagesWithSample as $key => $language)
								<div role="tabpanel" class="tab-pane {{ $language->id == Session::get('try')?'active':'' }}" id="try_{{ $language->symbol }}">
									<h4 class="modal-title">{{ trans('common.choosen.language') }}
										<strong class="red">{{ $language->name_short }}</strong>
									</h4>

									<p>{{ trans('common.try.language.now') }}</p>
									<audio class="sample" src="{{ $language->sample_path }}" preload="none"></audio>
								</div>
							@endforeach
						</div>

						{{--
						<ul class="nav nav-tabs" role="tablist">
							<span>Wybierz inny język</span>
							@foreach($languages as $key => $language)
								@if(!empty($language->sample))
									<li role="presentation" class="{{ $language->id == Session::get('try')?'active':'' }}">
										<a href="#try_{{ $language->symbol }}" aria-controls="{{ $language->symbol }}" role="tab" data-toggle="tab">{{ $language->name_short }}</a>
									</li>
								@endif
							@endforeach
						</ul>
						--}}
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Koniec Lekcja Próbna -->
@endif


<div class="modal fade" id="inactive" tabindex="-1" role="dialog" aria-labelledby="inactiveLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="tryLabel">{{ trans('languages.inactive.leave.your.data.part_1') }}
					<strong>{{ trans('languages.inactive.leave.your.data.part_2') }}</strong>
				</h4>
			</div>
			<div class="modal-body">
				{!! form_start($inactiveForm,['class' => 'modal-form']) !!}
				{!! form_widget($inactiveForm->name,['attr' => ['class' => '']]) !!}
				{!! form_widget($inactiveForm->email,['attr' => ['class' => '']]) !!}
				{!! form_widget($inactiveForm->phone,['attr' => ['class' => '']]) !!}

				{!! form_widget($inactiveForm->submit,['attr' => ['class' => '']]) !!}
				{!! form_end($inactiveForm) !!}
			</div>
		</div>
	</div>
</div>
@endif

<div class="last-buyer" style="display:none;">
	    <span class="img">
	        <img src="{{ asset('build/images/basket.png') }}" alt="basket">
	    </span>

	<p>
		{{ trans('checkout.last.bought') }}
		<span><strong data-container="buyer-name"></strong> {{ trans('checkout.from') }}
			<span data-container="buyer-city"></span></span> <b data-container="buyer-product"></b>
	</p>
</div>

@section('scripts')
	@if(Session::has('popup'))
		<script type="text/javascript">
			$(function () {
				$('#{{ Session::get('popup') }}').modal();
			});
		</script>
	@endif
@append

resources/views/part/remarketing.blade.php
<!-- Segment Pixel - INDO - Digital Commerce - Garcinia - DO NOT MODIFY -->
    <img src="‪https://secure.adnxs.com/seg?add=7124299&t=2‬" width="1" height="1" style="visibility: hidden" />
<!-- End of Segment Pixel -->

resources/views/part/searchForm.blade.php
{!! form_start($searchForm) !!}
<div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
{!! form_widget($goToPageForm->product, ['value' => $productSymbol]) !!}
{!! form_widget($searchForm->query, ['value' => $query ?? '']) !!}
    <span class="fa fa-search form-control-feedback left" aria-hidden="true"></span>
</div>
{!! form_row($searchForm->submit) !!}
{!! form_end($searchForm, false) !!}

resources/views/part/stay.blade.php
<script type="text/javascript">

    window.onbeforeunload = function() {

        var url = window.location.href;
        if(url.indexOf('popup=true')!=-1){
            window.setTimeout(function () {
                window.location = url.split('?')[0].replace('_main', '')+'up';
            }, 0);
            window.onbeforeunload = null;

            return '';
        }

//        if(document.cookie.indexOf('refreshed')==-1) {
//
//            document.cookie = 'refreshed=1';
//            params  = 'width='+screen.width;
//            params += ', height='+screen.height;
//            params += ', top=0, left=0';
//            params += ', fullscreen=yes';
//            window.open(window.location.href.replace('_main', '')+'up', '_newtab', params);
//            window.focus();
//
//        }

    };
</script>

resources/views/part/top.blade.php
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
                <span class="icon-bar"></span> <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('page.index') }}"><img src="{{ asset("build/images/logo.png") }}"
                                                                          alt="metode Emil Krebs"/></a>
        </div>
        @if(!Request::has('nolinks'))
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li {!! !is_null(Request::route()) && Request::route()->getName() == 'page.index'?'class="active"':'' !!}>
                        <a href="{{ route('page.index') }}">{{ trans('menu.homepage') }}</a>
                    </li>

                    {{-- <li {!! !is_null(Request::route()) && Request::route()->getName() == 'page.records'?'class="active"':'' !!}><a href="{{ route('page.records') }}">{{ trans('menu.records') }}</a></li> --}}

                    <li {!! !is_null(Request::route()) && Request::route()->getName() == 'page.lessons'?'class="active"':'' !!}>
                        <a href="{{ route('page.lessons') }}">{{ trans('menu.lessons') }}</a>
                    </li>

                    <li {!! !is_null(Request::route()) && Request::route()->getName() == 'page.languages'?'class="active"':'' !!}>
                        <a href="{{ route('page.languages') }}">{{ trans('menu.languages') }}</a>
                    </li>

                    <li {!! !is_null(Request::route()) && Request::route()->getName() == 'page.opinions'?'class="active"':'' !!}>
                        <a href="{{ route('page.opinions') }}">{{ trans('menu.opinions') }}</a>
                    </li>

                    <li {!! !is_null(Request::route()) && Request::route()->getName() == 'page.contact'?'class="active"':'' !!}>
                        <a href="{{ route('page.contact') }}">{{ trans('menu.contact') }}</a>
                    </li>

                    <li>
                        <a href="http://krebsmethod.co.id/blog">{{ trans('menu.blog') }}</a>
                    </li>

                    <li>
                        <a href="{{ route('page.try') }}" type="button" class="trigger">{{ trans('menu.try') }}</a>
                        {{--
                        <a href="#" class="trigger" type="button" data-toggle="modal" data-target="#{{ !Session::has('try')?'try':'test-lesson' }}">{{ trans('menu.try') }}</a>
                        --}}
                    </li>

                    <li><a href="{{ route('page.terms') }}">{{ trans('menu.terms') }}</a></li>
                    <li><a href="{{ route('page.languages') }}" style="color: #E64445;">{{ trans('menu.buy-now') }}</a>
                    </li>
                </ul>
            </div>
        @endif

        <div class="fb-like hidden-xs" data-href="https://www.facebook.com/KrebsMethodIndonesia/?fref=ts"
             data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>

    </div>
</nav>